### ISSUE TITLE
Issue with Automatic S3 Deployment

### ISSUE THREAD

**Issue by austinlangdon** [WP2Static/wp2static-addon-s3#5]
Hello!

We're having different experiences with WP2Static automated deployment to S3 vs AWS CLI manual deployment to S3.

When we deploy with WP2S, the static website does not display properly. We're able to repeatedly reproduce this issue. We have WP2Static installed with S3 and Zip deployment addons. We're also using CloudFront to serve the content.

Here are the steps to reproduce:

1. Clear all caches
2. Enqueue all jobs
3. Wait for deployment to complete (both S3 and zip)
4. S3 and Zip eployment complete - check the site - the site does not display like WP static site
![image](https://user-images.githubusercontent.com/8564275/78586300-1c5dff00-77f0-11ea-9084-4e6718b83f3f.png)

5. Delete all objects in S3 
6. Download static site ZIP file to local
7. Unzip static site
8. Copy static site to S3 using AWS CLI `aws s3 cp wp2static-processed-site s3://mywebsite.com --recursive`
9. Copy complete - check the site - static site displays exactly as WP site
![image](https://user-images.githubusercontent.com/8564275/78587852-79f34b00-77f2-11ea-8500-ec8c8139999f.png)

Any ideas on what could be causing this?

**Comment by john-shaffer** [comment]
The latest release, V7 alpha 002, has a bug where it sets the wrong Content-Type for CSS files, causing them to be ignored by the browser. This is fixed in https://github.com/WP2Static/wp2static-addon-s3/commit/c2c7b4103dd0e5d46a361e9e3b6c027feb7b03e8. Can you try getting the latest code with `git clone https://github.com/WP2Static/wp2static-addon-s3.git` and upload that to your plugins directory?

**Comment by austinlangdon** [comment]
Excellent! That was it. We will start using the latest in the repo for testing moving forward. Thank you @john-shaffer!
